### ISSUE TITLE
Error Pixelmon 9.1.9 [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null

### ISSUE THREAD

**Issue by Eisenwald** [CloverCard/CloverTrainerUtils#4]
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
7239 | Index: 1
7240 | Listeners:
7241 | 0: NORMAL
7242 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7243 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7244 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
7245 | java.lang.NullPointerException
7246 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
7247 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
7248 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
7249 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
7250 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
7251 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
7252 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
7253 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
7254 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
7255 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
7256 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
7257 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
7258 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
7259 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
7260 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
7261 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
7262 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
7263 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
7264 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
7265 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
7266 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
7267 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
7268 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
7269 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
7270 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
7271 | at java.base/java.lang.Thread.run(Thread.java:834)
```
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
7176 | Index: 1
7177 | Listeners:
7178 | 0: NORMAL
7179 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7180 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7181 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
7182 | java.lang.NullPointerException
7183 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
7184 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
7185 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
7186 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
7187 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
7188 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
7189 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
7190 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
7191 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
7192 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
7193 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
7194 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
7195 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
7196 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
7197 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
7198 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
7199 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
7200 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
7201 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
7202 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
7203 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
7204 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
7205 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
7206 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
7207 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
7208 | at java.base/java.lang.Thread.run(Thread.java:834)
```
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
7113 | Index: 1
7114 | Listeners:
7115 | 0: NORMAL
7116 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7117 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7118 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
7119 | java.lang.NullPointerException
7120 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
7121 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
7122 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
7123 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
7124 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
7125 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
7126 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
7127 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
7128 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
7129 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
7130 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
7131 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
7132 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
7133 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
7134 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
7135 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
7136 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
7137 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
7138 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
7139 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
7140 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
7141 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
7142 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
7143 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
7144 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
7145 | at java.base/java.lang.Thread.run(Thread.java:834)
```
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
7050 | Index: 1
7051 | Listeners:
7052 | 0: NORMAL
7053 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7054 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
7055 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
7056 | java.lang.NullPointerException
7057 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
7058 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
7059 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
7060 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
7061 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
7062 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
7063 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
7064 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
7065 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
7066 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
7067 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
7068 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
7069 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
7070 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
7071 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
7072 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
7073 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
7074 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
7075 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
7076 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
7077 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
7078 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
7079 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
7080 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
7081 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
7082 | at java.base/java.lang.Thread.run(Thread.java:834)
```
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
6987 | Index: 1
6988 | Listeners:
6989 | 0: NORMAL
6990 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
6991 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
6992 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
6993 | java.lang.NullPointerException
6994 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
6995 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
6996 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
6997 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
6998 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
6999 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
7000 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
7001 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
7002 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
7003 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
7004 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
7005 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
7006 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
7007 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
7008 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
7009 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
7010 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
7011 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
7012 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
7013 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
7014 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
7015 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
7016 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
7017 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
7018 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
7019 | at java.base/java.lang.Thread.run(Thread.java:834)
```
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
6924 | Index: 1
6925 | Listeners:
6926 | 0: NORMAL
6927 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
6928 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
6929 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
6930 | java.lang.NullPointerException
6931 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
6932 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
6933 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
6934 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
6935 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
6936 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
6937 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
6938 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
6939 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
6940 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
6941 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
6942 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
6943 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
6944 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
6945 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
6946 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
6947 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
6948 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
6949 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
6950 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
6951 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
6952 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
6953 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
6954 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
6955 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
6956 | at java.base/java.lang.Thread.run(Thread.java:834)
```
```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
--
6861 | Index: 1
6862 | Listeners:
6863 | 0: NORMAL
6864 | 1: ASM: com.clovercard.clovertrainerutils.listeners.ChatListener@7ecf7f5b onChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
6865 | 2: ASM: com.pixelmonmod.pixelmon.quests.listeners.EntityListeners@38493203 onNPCChat(Lcom/pixelmonmod/pixelmon/api/events/NPCChatEvent;)V
6866 | 3: net.minecraftforge.eventbus.EventBus$$Lambda$2698/0x0000000800badc40@f2b1b67
6867 | java.lang.NullPointerException
6868 | at com.pixelmonmod.pixelmon.entities.npcs.registry.NPCRegistryVillagers.getTranslatedChat(NPCRegistryVillagers.java:147)
6869 | at com.pixelmonmod.pixelmon.entities.npcs.NPCChatting.getChat(NPCChatting.java:273)
6870 | at com.clovercard.clovertrainerutils.listeners.ChatListener.onChat(ChatListener.java:16)
6871 | at net.minecraftforge.eventbus.ASMEventHandler_80_ChatListener_onChat_NPCChatEvent.invoke(.dynamic)
6872 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
6873 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
6874 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
6875 | at com.pixelmonmod.pixelmon.entities.npcs.NPCFisherman.interactWithNPC(NPCFisherman.java:122)
6876 | at com.pixelmonmod.pixelmon.entities.npcs.NPCEntity.func_184199_a(NPCEntity.java:512)
6877 | at net.minecraft.network.play.ServerPlayNetHandler.func_147340_a(ServerPlayNetHandlerMixin.java:2671)
6878 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:74)
6879 | at net.minecraft.network.play.client.CUseEntityPacket.func_148833_a(SourceFile:13)
6880 | at net.minecraft.network.PacketThreadUtil.mda83c75$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536)
6881 | at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
6882 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
6883 | at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
6884 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734)
6885 | at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159)
6886 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
6887 | at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717)
6888 | at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711)
6889 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
6890 | at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697)
6891 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921)
6892 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
6893 | at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by theonlytruegod** [comment]
what was the fix here?

**Comment by CloverCard** [comment]
I think this may have been resolved with the latest update. Please comment again if not, I'll leave this open for the time being.
